spring:
  application:
    name: springcloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Feign 是自带熔断器的，但默认是关闭的。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true